# Generated by Django 4.2.2 on 2024-06-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(blank=True, choices=[('Купля-продажа', (('b', 'Куплю'), ('s', 'Продам'))), ('Обмен', (('c', 'Обменяю'),))], max_length=1),
        ),
    ]
