# Generated by Django 4.2.2 on 2024-07-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_squashed_0005_alter_bb_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(blank=True, choices=[(None, 'Выберите тип публикуемого объявления'), ('Купля-продажа', (('b', 'Куплю'), ('s', 'Продам'))), ('Обмен', (('c', 'Обменяю'),))], max_length=1),
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to='rubric',
        ),
    ]
